/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_yappy_lua_LuaEngine */

#ifndef _Included_io_github_yappy_lua_LuaEngine
#define _Included_io_github_yappy_lua_LuaEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_yappy_lua_LuaEngine_DEFAULT_MEMORY_LIMIT
#define io_github_yappy_lua_LuaEngine_DEFAULT_MEMORY_LIMIT 16777216LL
#undef io_github_yappy_lua_LuaEngine_DEFAULT_INTR_INST_COUNT
#define io_github_yappy_lua_LuaEngine_DEFAULT_INTR_INST_COUNT 1000L
#undef io_github_yappy_lua_LuaEngine_VERSION_ARRAY_SIZE
#define io_github_yappy_lua_LuaEngine_VERSION_ARRAY_SIZE 4L
#undef io_github_yappy_lua_LuaEngine_LUA_MULTRET
#define io_github_yappy_lua_LuaEngine_LUA_MULTRET -1L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_BASE
#define io_github_yappy_lua_LuaEngine_LIB_BIT_BASE 1L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_PACKAGE
#define io_github_yappy_lua_LuaEngine_LIB_BIT_PACKAGE 2L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_COROUTINE
#define io_github_yappy_lua_LuaEngine_LIB_BIT_COROUTINE 4L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_TABLE
#define io_github_yappy_lua_LuaEngine_LIB_BIT_TABLE 8L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_IO
#define io_github_yappy_lua_LuaEngine_LIB_BIT_IO 16L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_OS
#define io_github_yappy_lua_LuaEngine_LIB_BIT_OS 32L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_STRING
#define io_github_yappy_lua_LuaEngine_LIB_BIT_STRING 64L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_MATH
#define io_github_yappy_lua_LuaEngine_LIB_BIT_MATH 128L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_UTF8
#define io_github_yappy_lua_LuaEngine_LIB_BIT_UTF8 256L
#undef io_github_yappy_lua_LuaEngine_LIB_BIT_DEBUG
#define io_github_yappy_lua_LuaEngine_LIB_BIT_DEBUG 512L
#undef io_github_yappy_lua_LuaEngine_LIB_ID_COUNT
#define io_github_yappy_lua_LuaEngine_LIB_ID_COUNT 10L
#undef io_github_yappy_lua_LuaEngine_LUA_OK
#define io_github_yappy_lua_LuaEngine_LUA_OK 0L
#undef io_github_yappy_lua_LuaEngine_LUA_YIELD
#define io_github_yappy_lua_LuaEngine_LUA_YIELD 1L
#undef io_github_yappy_lua_LuaEngine_LUA_ERRRUN
#define io_github_yappy_lua_LuaEngine_LUA_ERRRUN 2L
#undef io_github_yappy_lua_LuaEngine_LUA_ERRSYNTAX
#define io_github_yappy_lua_LuaEngine_LUA_ERRSYNTAX 3L
#undef io_github_yappy_lua_LuaEngine_LUA_ERRMEM
#define io_github_yappy_lua_LuaEngine_LUA_ERRMEM 4L
#undef io_github_yappy_lua_LuaEngine_LUA_ERRGCMM
#define io_github_yappy_lua_LuaEngine_LUA_ERRGCMM 5L
#undef io_github_yappy_lua_LuaEngine_LUA_ERRERR
#define io_github_yappy_lua_LuaEngine_LUA_ERRERR 6L
#undef io_github_yappy_lua_LuaEngine_LUA_TNIL
#define io_github_yappy_lua_LuaEngine_LUA_TNIL 0L
#undef io_github_yappy_lua_LuaEngine_LUA_TBOOLEAN
#define io_github_yappy_lua_LuaEngine_LUA_TBOOLEAN 1L
#undef io_github_yappy_lua_LuaEngine_LUA_TLIGHTUSERDATA
#define io_github_yappy_lua_LuaEngine_LUA_TLIGHTUSERDATA 2L
#undef io_github_yappy_lua_LuaEngine_LUA_TNUMBER
#define io_github_yappy_lua_LuaEngine_LUA_TNUMBER 3L
#undef io_github_yappy_lua_LuaEngine_LUA_TSTRING
#define io_github_yappy_lua_LuaEngine_LUA_TSTRING 4L
#undef io_github_yappy_lua_LuaEngine_LUA_TTABLE
#define io_github_yappy_lua_LuaEngine_LUA_TTABLE 5L
#undef io_github_yappy_lua_LuaEngine_LUA_TFUNCTION
#define io_github_yappy_lua_LuaEngine_LUA_TFUNCTION 6L
#undef io_github_yappy_lua_LuaEngine_LUA_TUSERDATA
#define io_github_yappy_lua_LuaEngine_LUA_TUSERDATA 7L
#undef io_github_yappy_lua_LuaEngine_LUA_TTHREAD
#define io_github_yappy_lua_LuaEngine_LUA_TTHREAD 8L
#undef io_github_yappy_lua_LuaEngine_CHECK_TYPE_BOOLEAN
#define io_github_yappy_lua_LuaEngine_CHECK_TYPE_BOOLEAN 0L
#undef io_github_yappy_lua_LuaEngine_CHECK_TYPE_INTEGER
#define io_github_yappy_lua_LuaEngine_CHECK_TYPE_INTEGER 1L
#undef io_github_yappy_lua_LuaEngine_CHECK_TYPE_NUMBER
#define io_github_yappy_lua_LuaEngine_CHECK_TYPE_NUMBER 2L
#undef io_github_yappy_lua_LuaEngine_CHECK_TYPE_STRING
#define io_github_yappy_lua_LuaEngine_CHECK_TYPE_STRING 3L
#undef io_github_yappy_lua_LuaEngine_CHECK_OPT_ALLOW_NIL
#define io_github_yappy_lua_LuaEngine_CHECK_OPT_ALLOW_NIL 65536L
#undef io_github_yappy_lua_LuaEngine_CHECK_TYPE_MASK
#define io_github_yappy_lua_LuaEngine_CHECK_TYPE_MASK 65535L
#undef io_github_yappy_lua_LuaEngine_LUA_HOOKCALL
#define io_github_yappy_lua_LuaEngine_LUA_HOOKCALL 0L
#undef io_github_yappy_lua_LuaEngine_LUA_HOOKRET
#define io_github_yappy_lua_LuaEngine_LUA_HOOKRET 1L
#undef io_github_yappy_lua_LuaEngine_LUA_HOOKLINE
#define io_github_yappy_lua_LuaEngine_LUA_HOOKLINE 2L
#undef io_github_yappy_lua_LuaEngine_LUA_HOOKCOUNT
#define io_github_yappy_lua_LuaEngine_LUA_HOOKCOUNT 3L
#undef io_github_yappy_lua_LuaEngine_LUA_HOOKTAILCALL
#define io_github_yappy_lua_LuaEngine_LUA_HOOKTAILCALL 4L
#undef io_github_yappy_lua_LuaEngine_LUA_MASKCALL
#define io_github_yappy_lua_LuaEngine_LUA_MASKCALL 1L
#undef io_github_yappy_lua_LuaEngine_LUA_MASKRET
#define io_github_yappy_lua_LuaEngine_LUA_MASKRET 2L
#undef io_github_yappy_lua_LuaEngine_LUA_MASKLINE
#define io_github_yappy_lua_LuaEngine_LUA_MASKLINE 4L
#undef io_github_yappy_lua_LuaEngine_LUA_MASKCOUNT
#define io_github_yappy_lua_LuaEngine_LUA_MASKCOUNT 8L
/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    getVersionInfo
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_getVersionInfo
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    newPeer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_github_yappy_lua_LuaEngine_newPeer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    deletePeer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_yappy_lua_LuaEngine_deletePeer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    setDebugHook
 * Signature: (JLio/github/yappy/lua/DebugHook;)V
 */
JNIEXPORT void JNICALL Java_io_github_yappy_lua_LuaEngine_setDebugHook
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    setHookMask
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_io_github_yappy_lua_LuaEngine_setHookMask
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    openLibs
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_openLibs
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    replacePrintFunc
 * Signature: (JLio/github/yappy/lua/LuaPrint;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_replacePrintFunc
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    loadString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_loadString
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    getTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_getTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    setTop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_github_yappy_lua_LuaEngine_setTop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    pushValues
 * Signature: (J[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_pushValues
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    getValues
 * Signature: (J[B[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_getValues
  (JNIEnv *, jclass, jlong, jbyteArray, jobjectArray);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    getCheckedValues
 * Signature: (J[I[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_getCheckedValues
  (JNIEnv *, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    pushNewTable
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_pushNewTable
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    setTableField
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_setTableField
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    pcall
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_pcall
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    getGlobal
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_getGlobal
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    setGlobal
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_setGlobal
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    setProxyCallback
 * Signature: (JLio/github/yappy/lua/FunctionRoot;)V
 */
JNIEXPORT void JNICALL Java_io_github_yappy_lua_LuaEngine_setProxyCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    pushProxyFunction
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_pushProxyFunction
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_yappy_lua_LuaEngine
 * Method:    testDestructor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_yappy_lua_LuaEngine_testDestructor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
