/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_yappy_lua_LuaEngine_FunctionRootImpl */

#ifndef _Included_io_github_yappy_lua_LuaEngine_FunctionRootImpl
#define _Included_io_github_yappy_lua_LuaEngine_FunctionRootImpl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
