/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
		System.out.println(new Library().someLibraryMethod());
		System.out.println(LuaNative.testMethod());
	}
}
